### ISSUE TITLE
Will not run on Ubuntu 16.04

### ISSUE THREAD

**Issue by nihar97** [omisego/plasma-cash#60]
Error when running python development.py. Using python3 and ubuntu.

`Traceback (most recent call last):
  File "deployment.py", line 3, in <module>
    Deployer().deploy_contract('RootChain/RootChain.sol')
  File "plasma-cash/plasma_cash/root_chain/deployer.py", line 48, in deploy_contract
    abi, bytecode, contract_name = self.compile_contract(path, args)
  File "plasma-cash/plasma_cash/root_chain/deployer.py", line 36, in compile_contract
    abi = compiled_sol['contracts'][file_name][contract_name]['abi']
KeyError: 'abi'
`

**Comment by HuangJi** [comment]
What's your solc version?

**Comment by nihar97** [comment]
Its 0.4.19.

**Comment by HuangJi** [comment]
Pls check the README, it can only run with 0.4.18 for now. We will fix this issue ASAP.
